= metafacture-csv-plugin
:toc:

A plugin for link:https://github.com/metafacture/metafacture-core[metafacture] that extends the standard CSV module.

== Build

image::https://jitpack.io/v/eberhardtj/metafacture-csv-plugin.svg[link="https://jitpack.io/#eberhardtj/metafacture-csv-plugin"]

```
gradlew test fatJar
```

Produces `metafacture-csv-VERSION-plugin.jar` in `build/libs` .

Place the build JAR inside the `plugins` directory of your `metafacture-core` distribution.

== Command Reference

|===
|Command | In | Out

|encode-csv
|StreamReceiver
|String

|===

=== encode-csv

==== Description

A simple encoder that constructs a table of __Comma-separated values__ (CSV).

Structure:

* Each record represents a row
** The sequential order of literal _values_ forms a *row*
** The sequential order of literal _names_ of the first record is used as _header_ (Optional)

CSV Dialect:

* Delimiter: ,
* Quote Char: "
* Line Terminator: \n
* Quoting: Quote All

Example Output:

```
"output","example","2018"
```

==== Syntax

```
encode-csv([separator],[includeHeader],[includeRecordId])
```

==== Parameters

* `separator`: Delimiter symbol (Default: comma)
* `includeHeader`: Add a header with column names (Default: false).
* `includeRecordId`: Add the record id as first element of each row (Default: false).

==== Example

Flux:

```
... | encoder-csv(separator=",", includeRecordId="true") | print;
```
